### ISSUE TITLE
App does not support a "Dialing Mode for SMS (3CX/API)" setting of "E164" ("Sync failed: corrupt response")

### ISSUE THREAD

**Issue by johnlescault** [michaelkourlas/voipms-sms-client#273]
It seems my app hasn't been syncing all day. Is there something bigger going on? Or is there something down at voip.ms by chance?

**Comment by michaelkourlas** [comment]
There appears to have been an API change.

Normally DIDs and contacts are presented as follows in the `getMMS` API response:

```
{"id":"78081872","date":"2024-05-20
19:19:59","type":"0","did":"5555555555","contact":"5555555555","message":"<message omitted>","col_media1":"","col_media2":"","col_media3":"","media":[]}
```

However, when a `did` parameter is specified in the request (to retrieve messages for a specific DID) the API now includes a prefix of `+1` for DIDs and contacts:

```
{"id":"78081872","date":"2024-05-20
19:19:59","type":"0","did":"+15555555555","contact":"+15555555555","message":"<message omitted>","col_media1":"","col_media2":"","col_media3":"","media":[]}
```

The app doesn't support this format.

**Comment by johnlescault** [comment]
Thanks for the quick reply! I assume this means we are stuck waiting for voip.ms to fix it at their end?

**Comment by Chimearaproductions** [comment]
It wasn't working for me most of the day, then suddenly started working again at around 7:30pm et.

**Comment by michaelkourlas** [comment]
This was addressed by VoIP.ms yesterday -- no action required.

**Comment by alex8065** [comment]
I am still getting this error. @michaelkourlas Could it be because I have multiple DIDs? In the phone numbers tab it says "stored locally but not found in Voip.ms account".

**Comment by michaelkourlas** [comment]
A user emailed me to tell me that you have to change the per-DID "Dialing Mode for SMS (3CX/API)" setting to NANPA. The app doesn't support the E164 format yet.

**Comment by michaelkourlas** [comment]
I'll be updating the app with E164 support at some point.

**Comment by michaelkourlas** [comment]
This will be addressed in the next release.
